name: Build and publish
on:
  push:
    branches:
      - master
jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1.10.0
        with:
          image-name: ninuxberry
          pi-gen-repository: mikysal78/pi-gen-ninux
          stage-list: stage0 stage1 stage2
          compression: zip
          compression-level: 9
          enable-ssh: 1
          export-last-stage-only: true
          github-token: ${{ github.token }}
          hostname: ninuxberry
          keyboard-keymap: it
          keyboard-layout: Italiana (IT)
          locale: it_IT.UTF-8
          password: 'ninux'
          pi-gen-dir: pi-gen
          pi-gen-version: arm64
          pubkey-only-ssh: 0
          pubkey-ssh-first-user: ''
          release: bookworm
          timezone: Europe/Rome
          username: ninux
          wpa-country: 'US'
          wpa-essid: 'ninux.org'
          wpa-password: 'Ninux:2025'
